platform :ios, '16.0'

target 'BodyThermometerProject' do
  use_frameworks!
  pod 'RxSwift', '6.9.0'
  pod 'RxCocoa', '6.9.0'
  pod 'SnapKit', '~> 5.7.0'
  pod 'RealmSwift', '10.42.0'
  pod 'RxRealm', '~> 5.0' 
  pod 'DGCharts'
  pod 'lottie-ios'
  pod 'ApphudSDK', '~> 3.6'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
end